// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyApTD13OabWJdrGSPXqKbo9ZAoZJYocEs4',
    appId: '1:149022161898:android:f82c708c91a7ea6177d093',
    messagingSenderId: '149022161898',
    projectId: 'student-sphere-7e3a3',
    storageBucket: 'student-sphere-7e3a3.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7493STj-ofaXRcEl26rRNwhlBzQ-tNqw',
    appId: '1:149022161898:web:1a176527b095d13777d093',
    messagingSenderId: '149022161898',
    projectId: 'student-sphere-7e3a3',
    authDomain: 'student-sphere-7e3a3.firebaseapp.com',
    storageBucket: 'student-sphere-7e3a3.firebasestorage.app',
    measurementId: 'G-56EEX5GHGN',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDFEYD_couxHjK-ZVER4Yw_HJDdUd2hqiU',
    appId: '1:149022161898:ios:0e0c133ae27ecc9b77d093',
    messagingSenderId: '149022161898',
    projectId: 'student-sphere-7e3a3',
    storageBucket: 'student-sphere-7e3a3.firebasestorage.app',
    iosBundleId: 'com.example.studentSphere',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDFEYD_couxHjK-ZVER4Yw_HJDdUd2hqiU',
    appId: '1:149022161898:ios:0e0c133ae27ecc9b77d093',
    messagingSenderId: '149022161898',
    projectId: 'student-sphere-7e3a3',
    storageBucket: 'student-sphere-7e3a3.firebasestorage.app',
    iosBundleId: 'com.example.studentSphere',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA7493STj-ofaXRcEl26rRNwhlBzQ-tNqw',
    appId: '1:149022161898:web:70d86e377bd2a09077d093',
    messagingSenderId: '149022161898',
    projectId: 'student-sphere-7e3a3',
    authDomain: 'student-sphere-7e3a3.firebaseapp.com',
    storageBucket: 'student-sphere-7e3a3.firebasestorage.app',
    measurementId: 'G-T5VTXT0J3T',
  );

}